const QuestionActionTypes = {
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
  FETCH_QUESTION_LIST_START: "FETCH_QUESTION_LIST_START",
  FETCH_QUESTION_LIST_SUCCESS: "FETCH_QUESTION_LIST_SUCCESS",
  FETCH_QUESTION_LIST_FAILURE: "FETCH_QUESTION_LIST_FAILURE",
};

export default QuestionActionTypes;
