const AnswerActionTypes = {
  FETCH_ANSWER_LIST_START: "FETCH_ANSWER_LIST_START",
  FETCH_ANSWER_LIST_SUCCESS: "FETCH_ANSWER_LIST_SUCCESS",
  FETCH_ANSWER_LIST_FAILURE: "FETCH_ANSWER_LIST_FAILURE",
};

export default AnswerActionTypes;
